In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("data/retail_store_sales.csv")

print(df)

      Transaction ID Customer ID       Category          Item  Price Per Unit  \
0        TXN_6867343     CUST_09     Patisserie   Item_10_PAT            18.5
1        TXN_3731986     CUST_22  Milk Products  Item_17_MILK            29.0
2        TXN_9303719     CUST_02       Butchers   Item_12_BUT            21.5
3        TXN_9458126     CUST_06      Beverages   Item_16_BEV            27.5
4        TXN_4575373     CUST_05           Food   Item_6_FOOD            12.5
...              ...         ...            ...           ...             ...
12570    TXN_9347481     CUST_18     Patisserie   Item_23_PAT            38.0
12571    TXN_4009414     CUST_03      Beverages    Item_2_BEV             6.5
12572    TXN_5306010     CUST_11       Butchers    Item_7_BUT            14.0
12573    TXN_5167298     CUST_04      Furniture    Item_7_FUR            14.0
12574    TXN_2407494     CUST_23           Food   Item_9_FOOD            17.0

       Quantity  Total Spent  Payment Method  Location Transaction Date  \
0          10.0        185.0  Digital Wallet    Online       2024-04-08
1           9.0        261.0  Digital Wallet    Online       2023-07-23
2           2.0         43.0     Credit Card    Online       2022-10-05
3           9.0        247.5     Credit Card    Online       2022-05-07
4           7.0         87.5  Digital Wallet    Online       2022-10-02
...         ...          ...             ...       ...              ...
12570       4.0        152.0     Credit Card  In-store       2023-09-03
12571       9.0         58.5            Cash    Online       2022-08-12
12572      10.0        140.0            Cash    Online       2024-08-24
12573       6.0         84.0            Cash    Online       2023-12-30
12574       3.0         51.0            Cash    Online       2022-08-06

      Discount Applied
0                 True
1                 True
2                False
3                  NaN
4                False
...                ...
12570              NaN
12571            False
12572              NaN
12573             True
12574              NaN

[12575 rows x 11 columns]

In [4]:
print("FIRST 5 ROWS:")
df.head()

FIRST 5 ROWS:

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [5]:
print("DATASET SHAPE:")
print(df.shape)

DATASET SHAPE:
(12575, 11)

In [6]:
print("DATASET INFORMATION:")
df.info()

DATASET INFORMATION:
<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(1), str(7)
memory usage: 1.1+ MB

In [7]:
print("MISSING VALUES:")
print(df.isnull().sum())

MISSING VALUES:
Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [8]:
print("DUPLICATE RECORDS:")
print("Number of duplicate rows:", df.duplicated().sum())

DUPLICATE RECORDS:
Number of duplicate rows: 0

In [9]:
print("DATA TYPES:")
print(df.dtypes)

DATA TYPES:
Transaction ID          str
Customer ID             str
Category                str
Item                    str
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method          str
Location                str
Transaction Date        str
Discount Applied     object
dtype: object

In [10]:
print("UNIQUE VALUES:")

for column in df.columns:
    print("\n" + column + ":")
    print(df[column].unique()[:20])

UNIQUE VALUES:

Transaction ID:
<StringArray>
['TXN_6867343', 'TXN_3731986', 'TXN_9303719', 'TXN_9458126', 'TXN_4575373',
 'TXN_7482416', 'TXN_3652209', 'TXN_1372952', 'TXN_9728486', 'TXN_2722661',
 'TXN_8776416', 'TXN_5422631', 'TXN_5874772', 'TXN_4413070', 'TXN_2490363',
 'TXN_1809665', 'TXN_7563311', 'TXN_9634894', 'TXN_4396807', 'TXN_4206593']
Length: 20, dtype: str

Customer ID:
<StringArray>
['CUST_09', 'CUST_22', 'CUST_02', 'CUST_06', 'CUST_05', 'CUST_07', 'CUST_21',
 'CUST_23', 'CUST_25', 'CUST_14', 'CUST_15', 'CUST_17', 'CUST_01', 'CUST_10',
 'CUST_04', 'CUST_13', 'CUST_18', 'CUST_08', 'CUST_20', 'CUST_12']
Length: 20, dtype: str

Category:
<StringArray>
[                        'Patisserie',                      'Milk Products',
                           'Butchers',                          'Beverages',
                               'Food',                          'Furniture',
      'Electric household essentials', 'Computers and electric accessories']
Length: 8, dtype: str

Item:
<StringArray>
[ 'Item_10_PAT', 'Item_17_MILK',  'Item_12_BUT',  'Item_16_BEV',
  'Item_6_FOOD',            nan,  'Item_1_FOOD',  'Item_16_FUR',
  'Item_22_BUT',   'Item_3_BUT',  'Item_2_FOOD',  'Item_24_PAT',
 'Item_16_MILK',  'Item_17_PAT',  'Item_13_EHE',   'Item_7_BEV',
   'Item_4_EHE', 'Item_10_FOOD',  'Item_14_FUR',  'Item_20_BUT']
Length: 20, dtype: str

Price Per Unit:
[18.5 29.  21.5 27.5 12.5  nan  5.  33.5 36.5  8.   6.5 39.5 24.5 23.
 35.  14.   9.5 41.  20.  38. ]

Quantity:
[10.  9.  2.  7.  8. nan  1.  3.  6.  4.  5.]

Total Spent:
[185.  261.   43.  247.5  87.5 200.   40.    nan  27.5 109.5  72.   52.
  45.5 237.   55.  232.  275.   23.  126.  105. ]

Payment Method:
<StringArray>
['Digital Wallet', 'Credit Card', 'Cash']
Length: 3, dtype: str

Location:
<StringArray>
['Online', 'In-store']
Length: 2, dtype: str

Transaction Date:
<StringArray>
['2024-04-08', '2023-07-23', '2022-10-05', '2022-05-07', '2022-10-02',
 '2023-11-30', '2023-06-10', '2024-04-02', '2023-04-26', '2024-03-14',
 '2024-12-14', '2025-01-12', '2023-09-09', '2022-05-20', '2022-05-22',
 '2022-05-11', '2024-11-16', '2022-04-17', '2022-02-07', '2025-01-13']
Length: 20, dtype: str

Discount Applied:
[True False nan]

In [11]:
df["Item"] = df["Item"].fillna("Unknown")

print("Missing Item values cleaned.")

Missing Item values cleaned.

In [12]:
df["Price Per Unit"] = df["Price Per Unit"].fillna(
    df["Price Per Unit"].median()
)

print("Missing Price Per Unit values cleaned.")

Missing Price Per Unit values cleaned.

In [13]:
df["Quantity"] = df["Quantity"].fillna(
    df["Quantity"].median()
)

print("Missing Quantity values cleaned.")

Missing Quantity values cleaned.

In [14]:
df["Total Spent"] = df["Total Spent"].fillna(
    df["Price Per Unit"] * df["Quantity"]
)

print("Missing Total Spent values cleaned.")

Missing Total Spent values cleaned.

In [15]:
df["Discount Applied"] = df["Discount Applied"].fillna(False)

print("Missing Discount Applied values cleaned.")

Missing Discount Applied values cleaned.

In [16]:
df = df.drop_duplicates()

print("Duplicate records removed.")
print("Remaining duplicates:", df.duplicated().sum())

Duplicate records removed.
Remaining duplicates: 0

In [17]:
df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"],
    errors="coerce"
)

print("Transaction Date data type:")
print(df["Transaction Date"].dtype)

Transaction Date data type:
datetime64[us]

In [18]:
df["Quantity"] = df["Quantity"].astype(int)

print("Quantity data type:")
print(df["Quantity"].dtype)

Quantity data type:
int64

In [19]:
df["Discount Applied"] = df["Discount Applied"].astype(bool)

print("Discount Applied data type:")
print(df["Discount Applied"].dtype)

Discount Applied data type:
bool

In [20]:
print("MISSING VALUES AFTER CLEANING:")
print(df.isnull().sum())

MISSING VALUES AFTER CLEANING:
Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

In [21]:
print("DUPLICATES AFTER CLEANING:")
print(df.duplicated().sum())

DUPLICATES AFTER CLEANING:
0

In [22]:
print("DATA TYPES AFTER CLEANING:")
print(df.dtypes)

DATA TYPES AFTER CLEANING:
Transaction ID                 str
Customer ID                    str
Category                       str
Item                           str
Price Per Unit             float64
Quantity                     int64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
Discount Applied              bool
dtype: object

In [23]:
print("CLEANED DATASET:")
df.head()

CLEANED DATASET:

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9,247.5,Credit Card,Online,2022-05-07,False
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7,87.5,Digital Wallet,Online,2022-10-02,False

In [24]:
print("FINAL DATASET SHAPE:")
print(df.shape)

FINAL DATASET SHAPE:
(12575, 11)

In [25]:
df.to_csv(
    "data/retail_store_sales_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!